add -h option to only remove this half and without data

diff --git a/remove-repository b/remove-repository
--- a/remove-repository
+++ b/remove-repository
@@ -7,15 +7,23 @@
 
 usage()
 {
-    echo "Usage: remove-repository [-f] fqrn" >&2
+    echo "Usage: remove-repository [-f] [-h] fqrn" >&2
+    echo " -f: force removal, don't ask for confirmation" >&2
+    echo " -h: remove only on this half of an HA pair, and leave data" >&2
     exit 1
 }
 
 DONTFORCE=true
-if [ "$1" = "-f" ]; then
-    DONTFORCE=false
-    shift
-fi
+HALFONLY=false
+while getopts :fh OPT; do
+    case $OPT in
+        f) DONTFORCE=false;;
+        h) HALFONLY=true;;
+        \?) echo "Invalid option: -$OPTARG" >&2
+            usage;;
+    esac
+done
+shift $((OPTIND-1))
 
 if [ $# != 1 ]; then
     usage
@@ -48,7 +56,11 @@ if [ ! -d "$STORAGE/$REPO" ]; then
 fi
 
 if $DONTFORCE; then
-    echo -n "Are you sure you want to remove $REPO from both machines? "
+    if $HALFONLY; then
+        echo -n "Are you sure you want to remove $REPO on this machine? "
+    else
+        echo -n "Are you sure you want to remove $REPO from both machines? "
+    fi
     read ANS
     case $ANS in
 	y*|Y*);;
@@ -58,25 +70,27 @@ fi
 
 set -ex
 
-if [ -f /etc/krb5.keytab ]; then
+if ! $HALFONLY && [ -f /etc/krb5.keytab ]; then
     export KRB5CCNAME=FILE:/tmp/krb5cc_root_hastratum1
     PATH=$PATH:/usr/krb5/bin:/usr/kerberos/bin kinit -k host/$THISHOST
 fi
 
-ssh $OTHERHOST rm -f $SRV/$REPO
+if ! $HALFONLY; then ssh $OTHERHOST rm -f $SRV/$REPO; fi
 rm -f $SRV/$REPO
-ssh $OTHERHOST rm -rf /var/spool/cvmfs/$REPO
+if ! $HALFONLY; then ssh $OTHERHOST rm -rf /var/spool/cvmfs/$REPO; fi
 rm -rf /var/spool/cvmfs/$REPO
-ssh $OTHERHOST rm -rf /etc/cvmfs/repositories.d/$REPO
+if ! $HALFONLY; then ssh $OTHERHOST rm -rf /etc/cvmfs/repositories.d/$REPO; fi
 rm -rf /etc/cvmfs/repositories.d/$REPO
-if [ -n "$SHORTREPO" ]; then
-    ssh $OTHERHOST rm -f $STORAGE/$SHORTREPO
-    rm -f $STORAGE/$SHORTREPO
+if ! $HALFONLY; then
+    if [ -n "$SHORTREPO" ]; then
+        ssh $OTHERHOST rm -f $STORAGE/$SHORTREPO
+        rm -f $STORAGE/$SHORTREPO
+    fi
+    ssh $OTHERHOST rm -rf $STORAGE/$REPO
+    rm -rf $STORAGE/$REPO
 fi
-ssh $OTHERHOST rm -rf $STORAGE/$REPO
-rm -rf $STORAGE/$REPO
 if [ "`echo $STORAGE/info/*`" != "$STORAGE/info/*" ]; then
     # cvmfs-server 2.2.X or later
     cvmfs_server update-info -e
-    rsync -a $STORAGE/info $OTHERHOST:$STORAGE
+    if ! $HALFONLY; then rsync -a $STORAGE/info $OTHERHOST:$STORAGE; fi
 fi
